const CASE="CTI-2026-0142",W="0x71A3F2C8D91E6B47A2F91C84E0C793F293F2A93F2";
const S={newNode:false,alerted:false,crossAlert:false};
const TX=[
{ts:"2026-09-21 14:20",h:"0x19ab...72f1",f:"0x19C...82A1",t:"0x71A...93F2",a:"USDT",v:"18,500",c:"Transfer",e:"Suspect Wallet (victim-reported)",s:"Verified",blk:18442031,m:"transfer(address,uint256)",g:"0.0021 ETH",ev:"Transfer(0x19C…, 0x71A…, 18500e6)"},
{ts:"2026-09-21 14:32",h:"0x9f31...a82d",f:"0x71A...93F2",t:"0xA81...44C1",a:"USDT",v:"18,500",c:"Transfer",e:"Unknown Wallet",s:"Verified",blk:18442049,m:"transfer(address,uint256)",g:"0.0019 ETH",ev:"Transfer(0x71A…, 0xA81…, 18500e6)"},
{ts:"2026-09-21 14:36",h:"0x81ab...e913",f:"0x71A...93F2",t:"0xBridge...7A21",a:"ETH",v:"4.82",c:"Contract Call",e:"Bridge Candidate",s:"Candidate",blk:18442058,m:"depositETH(address,uint32)",g:"0.0044 ETH",ev:"DepositInitiated(dest=Polygon, amt=4.82e18)"},
{ts:"2026-09-21 14:41",h:"0x72bc...f182",f:"0xBridge...7A21",t:"0x92F...18B4",a:"USDT",v:"18,320",c:"Polygon Mint",e:"Unknown Entity",s:"Correlated",blk:"61,204,377 (Polygon)",m:"onReceive(bytes)",g:"0.011 MATIC",ev:"Minted(0x92F…, 18320e6)"},
{ts:"2026-09-22 09:12",h:"0x3de9...5c40",f:"0x92F...18B4",t:"0xEXC...91D2",a:"USDT",v:"18,300",c:"Transfer",e:"Exchange Candidate",s:"Review",blk:"61,219,840 (Polygon)",m:"transfer(address,uint256)",g:"0.008 MATIC",ev:"Transfer(0x92F…, 0xEXC…, 18300e6)"}];
const CASES=[[CASE,"0x71A...93F2","Ethereum → Polygon","14 min ago","Active","High"],["CTI-2026-0139","0x8C2...A781","Ethereum","1 hr ago","Review","Medium"],["CTI-2026-0135","0x92F...18B4","Polygon","3 hrs ago","Monitoring","Low"]];
const rk=r=>`<span class="b ${r=="High"?"rd":r=="Medium"?"wa":"ok"}">${r}</span>`;
const NS=[
{id:"v",t:"Victim Wallet",a:"0x19C...82A1",net:"Ethereum",c:"bl",x:20,y:170,cls:"Wallet (victim-reported)",conf:"Verified",parent:null,risk:null,first:"2026-09-21 14:18",last:"2026-09-21 14:20",tx:1,inAmt:"0",outAmt:"18,500 USDT",why:["Address supplied in the complaint","Outgoing transfer observed on-chain"],ev:["EV-001"]},
{id:"s",t:"Suspect Wallet",a:"0x71A...93F2",net:"Ethereum",c:"rd",x:180,y:170,cls:"Investigation Lead",conf:"High",parent:"v",risk:87,level:"HIGH",first:"2026-08-14",last:"2026-09-21 14:28",tx:47,inAmt:"18,500 USDT",outAmt:"18,500 USDT + 1.10 ETH",factors:[["Cross-chain movement",20],["Bridge interaction",18],["Rapid fund movement",15],["Multiple intermediaries",14],["High-value transfer",12],["Exchange proximity",8]],why:["High-value transfers","Multiple intermediary wallets","Cross-chain movement","Bridge interaction","Rapid fund movement","Destination linked to exchange candidate"],ev:["EV-001","EV-002","EV-005"]},
{id:"A",t:"Wallet A",a:"0x4d1...22e9",net:"Ethereum",c:"bl",x:340,y:60,cls:"Wallet (branch)",conf:"Low",parent:"s",risk:25,level:"LOW",first:"2026-09-21 14:24",last:"2026-09-21 14:26",tx:2,inAmt:"1.10 ETH",outAmt:"1.05 ETH",factors:[["Received from suspect wallet",15],["Single onward hop",10]],why:["Received funds directly from the suspect wallet","Forwarded onward within 2 minutes"],ev:["EV-005","EV-006"]},
{id:"C",t:"Wallet C",a:"0x2b9...9cf1",net:"Ethereum",c:"gy",x:500,y:60,cls:"Unknown Entity",conf:"Low",parent:"A",risk:12,level:"LOW",first:"2026-09-21 14:26",last:"2026-09-21 14:26",tx:1,inAmt:"1.05 ETH",outAmt:"0",why:["Dead-end branch; no further onward activity observed"],ev:["EV-006"]},
{id:"B1",t:"Intermediate Wallet 1",a:"0xA81...44C1",net:"Ethereum",c:"bl",x:340,y:270,cls:"Wallet (intermediary)",conf:"Medium",parent:"s",risk:40,level:"LOW",first:"2026-09-21 14:28",last:"2026-09-21 14:31",tx:2,inAmt:"18,500 USDT",outAmt:"18,450 USDT",factors:[["Received from suspect wallet",20],["Forwarded within 3 minutes",20]],why:["Received the full reported amount from the suspect wallet","Forwarded onward within 3 minutes"],ev:["EV-002","EV-007"]},
{id:"B2",t:"Intermediate Wallet 2",a:"0x6f3...b872",net:"Ethereum",c:"bl",x:500,y:270,cls:"Wallet (intermediary)",conf:"Medium",parent:"B1",risk:46,level:"MEDIUM",first:"2026-09-21 14:31",last:"2026-09-21 14:36",tx:2,inAmt:"18,450 USDT",outAmt:"4.82 ETH",factors:[["Received from intermediary wallet",18],["Converted asset before bridge deposit",28]],why:["Received from Intermediate Wallet 1","Converted value ahead of a bridge contract deposit"],ev:["EV-007","EV-003"]},
{id:"br",t:"Bridge Candidate",a:"0xBridge...7A21",net:"Ethereum",c:"pu",x:660,y:270,cls:"BRIDGE CANDIDATE",conf:"High",parent:"B2",risk:82,level:"HIGH",first:"2026-09-21 14:36",last:"2026-09-21 14:36",tx:1,inAmt:"4.82 ETH",outAmt:"18,320 USDT (Polygon)",factors:[["Bridge contract interaction",30],["Cross-chain correlation",25],["Known contract behaviour",15],["Destination-chain activity",12]],why:["Smart-contract interaction","Known contract behaviour","Cross-chain activity correlation","Destination-chain activity"],ev:["EV-003","EV-004"]},
{id:"p",t:"Destination Wallet",a:"0x92F...18B4",net:"Polygon",c:"or",x:820,y:270,cls:"Correlated destination (Unknown Entity)",conf:"High",parent:"br",risk:68,level:"MEDIUM",first:"2026-09-21 14:41",last:"2026-09-22 09:12",tx:2,inAmt:"18,320 USDT",outAmt:"18,300 USDT",factors:[["Cross-chain correlation",30],["Temporal proximity",20],["Amount closely matches deposit",18]],why:["Received USDT 3 min 42 sec after the bridge deposit event","Amount matches deposit less fee"],ev:["EV-004","EV-008"]},
{id:"x",t:"Exchange Candidate",a:"0xEXC...91D2",net:"Polygon",c:"gy",x:980,y:270,cls:"Exchange Candidate (unverified)",conf:"Medium",parent:"p",risk:55,level:"MEDIUM",first:"2026-09-22 09:12",last:"2026-09-22 09:12",tx:1,inAmt:"18,300 USDT",outAmt:"—",factors:[["Downstream of correlated funds",25],["High inbound volume from many senders",20],["Identity not confirmed",10]],why:["Receives funds from many senders","Label not confirmed; identity inconclusive"],ev:["EV-008"]}];
const NEWN={id:"z",t:"New Destination",a:"0x5D1...C3E0",net:"Polygon",c:"rd",x:980,y:400,cls:"Investigation Lead (new)",conf:"Medium",parent:"p",risk:58,level:"MEDIUM",first:"just now",last:"just now",tx:1,inAmt:"2,400 USDT",outAmt:"0",factors:[["First seen in monitoring window",30],["Linked to correlated destination",28]],why:["First seen 3 minutes ago","Received 2,400 USDT from 0x92F...18B4"],ev:["EV-009"]};
const EDG=[
{id:0,f:"v",t:"s",as:"USDT",am:"18,500",h:"0x19ab...72f1",ts:"2026-09-21 14:20",net:"Ethereum",ty:"Transfer",c:"bl",ev:"EV-001",corr:"—",conf:"—"},
{id:1,f:"s",t:"A",as:"ETH",am:"1.10",h:"0x5a2c...d901",ts:"2026-09-21 14:24",net:"Ethereum",ty:"Transfer",c:"bl",ev:"EV-005",corr:"—",conf:"—"},
{id:2,f:"A",t:"C",as:"ETH",am:"1.05",h:"0x77e1...b204",ts:"2026-09-21 14:26",net:"Ethereum",ty:"Transfer",c:"bl",ev:"EV-006",corr:"—",conf:"—"},
{id:3,f:"s",t:"B1",as:"USDT",am:"18,500",h:"0x9f31...a82d",ts:"2026-09-21 14:28",net:"Ethereum",ty:"Transfer",c:"bl",ev:"EV-002",corr:"—",conf:"—"},
{id:4,f:"B1",t:"B2",as:"USDT",am:"18,450",h:"0x2c9d...7e10",ts:"2026-09-21 14:31",net:"Ethereum",ty:"Transfer",c:"bl",ev:"EV-007",corr:"MEDIUM",conf:"—"},
{id:5,f:"B2",t:"br",as:"ETH",am:"4.82",h:"0x81ab...e913",ts:"2026-09-21 14:36",net:"Ethereum",ty:"Contract call",c:"pu",ev:"EV-003",corr:"—",conf:"—"},
{id:6,f:"br",t:"p",as:"USDT",am:"18,320",h:"0x72bc...f182",ts:"2026-09-21 14:41",net:"Ethereum → Polygon",ty:"Cross-chain transition",c:"or",ev:"EV-004",corr:"HIGH",conf:"HIGH",cross:true,diff:"3 min 42 sec"},
{id:7,f:"p",t:"x",as:"USDT",am:"18,300",h:"0x3de9...5c40",ts:"2026-09-22 09:12",net:"Polygon",ty:"Transfer",c:"rd",ev:"EV-008",corr:"MEDIUM",conf:"—"}];
const NEWE={id:8,f:"p",t:"z",as:"USDT",am:"2,400",h:"0xa1f4...7c22",ts:"just now",net:"Polygon",ty:"Transfer",c:"rd",ev:"EV-009",corr:"—",conf:"—"};
const EVID={"EV-001":"18,500 USDT transferred from victim to suspect wallet","EV-002":"18,500 USDT forwarded to Intermediate Wallet 1","EV-003":"Bridge candidate contract interaction","EV-004":"Polygon destination activity, 3 min 42 sec after deposit","EV-005":"Suspect wallet funds Wallet A (branch)","EV-006":"Wallet A forwards to Wallet C (dead end)","EV-007":"Intermediate Wallet 1 forwards to Intermediate Wallet 2","EV-008":"Destination wallet forwards to exchange candidate","EV-009":"New destination wallet observed in monitoring"};
const PRIOR=[["s","HIGH","Cross-chain + multiple hops"],["br","HIGH","Cross-chain correlation"],["p","MEDIUM","Correlated destination activity"],["x","FOLLOW-UP","Downstream of correlated funds"]];
const F={n:"All",a:"All",dir:"All",depth:"All"},G={x:0,y:0,k:1};let sel=null,pathMode=false;
const CL={bl:"#2563EB",pu:"#7C3AED",or:"#EA580C",gn:"#16A34A",gy:"#64748B",rd:"#DC2626"};
const LG=[["bl","Wallet"],["pu","Smart contract"],["or","Cross-chain edge"],["gn","Verified entity"],["gy","Unknown entity"],["rd","Investigation lead"]];
const $=s=>document.querySelector(s),app=$("#app");
function toast(m){const t=$("#toast");t.textContent=m;t.style.display="block";clearTimeout(t._t);t._t=setTimeout(()=>t.style.display="none",2600)}
function drawer(h){const d=$("#dr");d.innerHTML=`<button class="g" onclick="closeD()" style="float:right">Close</button>`+h;d.style.display="block"}
function closeD(){$("#dr").style.display="none"}
function modal(h){const o=$("#ov");o.innerHTML=`<div class="md">${h}<p style="text-align:right"><button class="g" onclick="closeM()">Close</button></p></div>`;o.style.display="flex"}
function closeM(){$("#ov").style.display="none"}
function head(t,s){return `<h1>${t}</h1><p class="sub">${s}</p>`}
function tabs(p){const b=`#/investigation/${CASE}`;return `<p>${[["",p=="d"?1:0,"Transactions"],["/fund-flow",p=="f",'Fund Flow'],["/cross-chain",p=="c","Cross-Chain"],["/evidence",p=="e","Evidence"]].map(x=>`<a class="h" style="margin-right:14px;${x[1]?"font-weight:700":""}" href="${b}${x[0]}">${x[2]}</a>`).join("")}</p>`}
function txDrawer(i){const x=TX[i];drawer(`<h2>Transaction details</h2><dl><dt>Transaction hash</dt><dd class="m">${x.h}</dd><dt>Network</dt><dd>${x.blk.toString().includes("Polygon")?"Polygon":"Ethereum"}</dd><dt>Block</dt><dd>${x.blk}</dd><dt>Timestamp</dt><dd>${x.ts} UTC</dd><dt>From</dt><dd class="m">${x.f}</dd><dt>To</dt><dd class="m">${x.t}</dd><dt>Asset / Amount</dt><dd>${x.v} ${x.a}</dd><dt>Gas</dt><dd>${x.g}</dd><dt>Contract</dt><dd>${x.c}</dd><dt>Method</dt><dd class="m">${x.m}</dd><dt>Events</dt><dd class="m">${x.ev}</dd></dl>
<h2>Evidence source</h2><ul class="chk"><li>✓ Transaction hash</li><li>✓ Block</li><li>✓ Timestamp</li><li>✓ On-chain transfer</li></ul><span class="b ok">Observed on-chain evidence</span><p><button onclick="explorer(${i})">View on-chain record</button> <button class="g" onclick="closeD();toast('Transaction added to fund-flow graph.');location.hash='#/investigation/'+CASE+'/fund-flow'">ADD TO FUND FLOW</button></p>`)}
function explorer(i){const x=TX[i];modal(`<h2>Simulated explorer record</h2><p class="mu">This is mock data. No live explorer or node was queried.</p><p class="m">${x.h}<br>Block ${x.blk}<br>${x.f} → ${x.t}<br>${x.v} ${x.a}<br>Status: Success (simulated)</p>`)}
const allN=()=>S.newNode?[...NS,NEWN]:NS,allE=()=>S.newNode?[...EDG,NEWE]:EDG;
const hx=h=>{const i=TX.findIndex(t=>t.h==h);return i<0?`<span class="m">${h}</span>`:`<a class="h m" onclick="txDrawer(${i})">${h}</a>`};
const st=s=>`<span class="b ${{Verified:"ok",Correlated:"te",Candidate:"pu",Unknown:"mu",Review:"wa"}[s]||"mu"}">${s}</span>`;
const nb=n=>`<span class="nb ${n=="Polygon"?"pg":"eth"}">${n}</span>`;
const evList=ids=>`<div><b>Supporting evidence</b><div class="evl">${ids.map(id=>`<div class="evi" onclick="openEv('${id}')"><b>${id}</b><span class="mu"> — ${EVID[id]}</span></div>`).join("")}</div></div>`;
function openEv(id){const N=allN(),E=allE(),eg=E.find(e=>e.ev==id);modal(`<h2>${id}</h2><p>${EVID[id]}</p>${eg?`<dl class="kv"><dt>TX hash</dt><dd class="m">${eg.h}</dd><dt>Timestamp</dt><dd>${eg.ts}</dd><dt>Network</dt><dd>${nb(eg.net.split(" ")[0])}</dd></dl>`:""}<p class="mu">Graph → transaction → evidence. Close to return to the graph.</p>`)}
function pathTo(id){const N=allN(),path=[];let cur=N.find(n=>n.id==id);while(cur){path.unshift(cur.id);cur=cur.parent?N.find(n=>n.id==cur.parent):null}return path}
function pathStats(path){const N=allN(),E=allE(),edges=[];for(let i=0;i<path.length-1;i++)edges.push(E.find(e=>e.f==path[i]&&e.t==path[i+1]));const nets=new Set(path.map(id=>N.find(n=>n.id==id).net));const cross=edges.filter(e=>e&&e.cross).length;const riskMax=Math.max(...path.map(id=>N.find(n=>n.id==id).risk||0));const lvl=riskMax>=75?"HIGH":riskMax>=45?"MEDIUM":"LOW";return{hops:path.length,nets:nets.size,cross,risk:riskMax,lvl,bridge:edges.some(e=>e&&e.ty=="Contract call")?1:0,amt:"18,500 USDT"}}
function ent(n){const risky=n.risk!=null;return `<h3 style="margin:0 0 4px">Selected node</h3><b>${n.t}</b><dl class="kv"><dt>Wallet</dt><dd class="m">${n.a}</dd><dt>Network</dt><dd>${nb(n.net)}</dd><dt>Type</dt><dd>${n.cls}</dd><dt>Transactions</dt><dd>${n.tx}</dd><dt>Total incoming</dt><dd>${n.inAmt}</dd><dt>Total outgoing</dt><dd>${n.outAmt}</dd><dt>First / last observed</dt><dd>${n.first} → ${n.last}</dd></dl>
${risky?`<div class="rs"><div class="rsn">${n.risk} / 100</div><div><b style="color:${n.level=="HIGH"?"var(--rd)":n.level=="MEDIUM"?"var(--wa)":"var(--ok)"}">${n.level} RISK</b><div class="mu" style="font-size:12px">Analytical score from simulated signals — not an identity conclusion.</div></div></div>
<b>Signals</b><ul class="chk">${n.why.map(w=>`<li>✓ ${w}</li>`).join("")}</ul>
<details><summary class="mu" style="cursor:pointer">Why this score? (risk factors)</summary><div class="rf">${n.factors.map(f=>`<div class="rfr"><span>${f[0]}</span><b>+${f[1]}</b></div>`).join("")}<div class="rfr" style="border-top:1px solid var(--ln);margin-top:4px;padding-top:4px"><span>Total</span><b>${n.risk}</b></div></div></details>`:`<p class="mu">Reported starting point; not risk-scored.</p>`}
${evList(n.ev)}
<div class="fb" style="margin-top:10px">${n.parent!==undefined&&n.parent!==null?`<button onclick="investigatePath('${n.id}')">INVESTIGATE THIS PATH</button>`:""}<button class="g" onclick="location.hash='#/investigation/'+CASE">VIEW EVIDENCE</button></div>
<p class="mu" style="margin-top:8px">Observed behaviour warrants further investigation. This is an investigation lead, not an identity claim.</p>`}
function einsp(e){const N=allN(),a=N.find(n=>n.id==e.f),b=N.find(n=>n.id==e.t);return `<h3 style="margin:0 0 6px">Transaction</h3><b>${a.t} → ${b.t}</b><dl class="kv"><dt>Transaction hash</dt><dd>${hx(e.h)}</dd><dt>From</dt><dd class="m">${a.a}</dd><dt>To</dt><dd class="m">${b.a}</dd><dt>Amount</dt><dd>${e.am} ${e.as}</dd><dt>Timestamp</dt><dd>${e.ts}</dd><dt>Network</dt><dd>${e.net}</dd><dt>Transaction type</dt><dd>${e.ty}</dd><dt>Evidence ID</dt><dd><a class="h" onclick="openEv('${e.ev}')">${e.ev}</a></dd><dt>Correlation</dt><dd>${e.corr}</dd><dt>Confidence</dt><dd>${e.conf}</dd>${e.cross?`<dt>Time difference</dt><dd>${e.diff}</dd>`:""}</dl>${e.cross?`<div class="gap" style="margin-top:8px"><b>CROSS-CHAIN CORRELATION</b><p style="margin:4px 0 0">Bridge-mediated movement consistent with observed evidence. Not a confirmed bridge.</p></div>`:""}`}
function aiPanel(){const N=allN();let n=sel&&sel.t=="n"?N.find(x=>x.id==sel.id):null;if(!n||n.risk==null)return `<b>AI investigation intelligence</b><p class="mu" style="margin-top:6px">Select a risk-scored node to see explainable AI reasoning.</p>`;
return `<b>AI investigation intelligence</b><div class="rs" style="margin-top:8px"><div class="rsn">${n.risk}/100</div><div><b>${n.level}</b><div class="mu" style="font-size:12px">Priority: ${n.risk>=75?"INVESTIGATE FIRST":n.risk>=45?"REVIEW SOON":"MONITOR"}</div></div></div>
<b>Reasoning</b><ul class="chk">${n.why.map(w=>`<li>✓ ${w}</li>`).join("")}</ul>
<p><b>Recommended next step</b><br><span class="mu">Trace the highlighted path from ${n.a} toward the final connected entity.</span></p>
<b>Suggested investigation order</b><ol style="padding-left:18px;margin:6px 0">${PRIOR.map(p=>`<li>${N.find(x=>x.id==p[0]).t} — <b>${p[1]}</b></li>`).join("")}</ol>
<button class="g" onclick="toast('AI reasoning is derived from the simulated signals shown above.')">WHY?</button>`}
function priorityPanel(){const N=allN();return `<b>Today's investigation priorities</b><div class="evl" style="margin-top:6px">${PRIOR.map(p=>{const n=N.find(x=>x.id==p[0]);return `<div class="evi" onclick="selN('${p[0]}')"><b>${n.t}</b> <span class="b ${p[1]=="HIGH"?"rd":p[1]=="MEDIUM"?"wa":"mu"}">${p[1]}</span><br><span class="mu">Risk ${n.risk} · ${p[2]}</span></div>`}).join("")}</div>`}
function pathBanner(){if(!pathMode||!sel||sel.t!="n")return "";const path=pathTo(sel.id),st=pathStats(path);if(path.length<2)return "";
return `<div class="pathb"><b>INVESTIGATION PATH</b> <span class="mu">${st.hops} hops · ${st.nets} networks/contracts · ${st.amt} · 3 min 42 sec cross-chain correlation</span><div class="fb" style="margin-top:6px"><span class="b ${st.lvl=="HIGH"?"rd":st.lvl=="MEDIUM"?"wa":"ok"}">PATH RISK ${st.lvl} — ${st.risk}/100</span><span class="mu">${st.cross} cross-chain event(s) · ${st.bridge} bridge candidate</span></div><p class="mu" style="margin:6px 0 0">Funds move from the suspect wallet through intermediary addresses before a correlated cross-chain movement to Polygon. The strongest investigative lead is the bridge-to-destination segment.</p></div>`}
function insp(){if(!sel)return `<h3 style="margin:0 0 6px">Inspector</h3><p class="mu">Select a node or an edge to see the evidence behind it.</p>`;return sel.t=="n"?ent(allN().find(n=>n.id==sel.id)):einsp(allE().find(e=>e.id==sel.id))}
const selN=id=>{sel={t:"n",id};pathMode=false;render()},selE=id=>{sel={t:"e",id};render()};
function investigatePath(id){sel={t:"n",id};pathMode=true;render();toast("Path highlighted — unrelated nodes dimmed.")}
const ap=()=>{const g=$("#gg");g&&g.setAttribute("transform",`translate(${G.x} ${G.y}) scale(${G.k})`)};
function zoom(d){G.k=Math.min(2.5,Math.max(.5,G.k*d));ap()}
function gInit(){const v=$("#gs");if(!v)return;ap();v.addEventListener("wheel",e=>{e.preventDefault();zoom(e.deltaY<0?1.1:.9)},{passive:false});let d=null;
v.addEventListener("pointerdown",e=>{if(e.target.closest(".node,.edge"))return;d={x:e.clientX,y:e.clientY,gx:G.x,gy:G.y};v.setPointerCapture(e.pointerId)});
v.addEventListener("pointermove",e=>{if(!d)return;const r=1100/v.clientWidth;G.x=d.gx+(e.clientX-d.x)*r;G.y=d.gy+(e.clientY-d.y)*r;ap()});v.addEventListener("pointerup",()=>d=null)}
const seg=(k,o)=>`<span class="sg"><span class="mu">${{n:"Network",a:"Asset",dir:"Direction",depth:"Expand"}[k]}</span>${o.map(v=>`<button class="${F[k]==v?"":"g"}" onclick="F.${k}='${v}';render()">${v}</button>`).join("")}</span>`;
function gsvg(){const N=allN(),E=allE(),P=id=>N.find(n=>n.id==id);
const onPath=pathMode&&sel&&sel.t=="n"?new Set(pathTo(sel.id)):null;
const depthOf=id=>{let d=0,c=P(id);while(c&&c.parent){d++;c=P(c.parent)}return d};
const selDepth=sel&&sel.t=="n"?depthOf(sel.id):null;
const vn=n=>{if(F.n!="All"&&n.net!=F.n)return false;if(F.depth!="All"&&selDepth!=null){const dd=Math.abs(depthOf(n.id)-selDepth);if(F.depth=="1-hop"&&dd>1)return false;if(F.depth=="2-hop"&&dd>2)return false}return true};
const ve=e=>vn(P(e.f))&&vn(P(e.t))&&(F.a=="All"||e.as==F.a)&&(F.dir=="All"||!sel||sel.t!="n"||(F.dir=="Incoming"?e.t==sel.id:e.f==sel.id)||!(e.f==sel.id||e.t==sel.id)===false);
const connected=sel&&sel.t=="n"?new Set(E.filter(e=>e.f==sel.id||e.t==sel.id).flatMap(e=>[e.f,e.t])):null;
const es=E.filter(ve).map(e=>{const a=P(e.f),b=P(e.t),onP=onPath&&onPath.has(e.f)&&onPath.has(e.t),dim=(onPath&&!onP)||(!onPath&&connected&&!(e.f==sel.id||e.t==sel.id));
const ver=a.y==b.y,x1=ver?a.x+150:a.x+75,y1=ver?a.y+32:a.y+64,x2=ver?b.x:b.x+75,y2=ver?b.y+32:b.y,mx=(x1+x2)/2,my=(y1+y2)/2,c=CL[e.c],z=sel&&sel.t=="e"&&sel.id==e.id;
return `<g class="edge" opacity="${dim?.18:1}" onclick="selE(${e.id})"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="transparent" stroke-width="16"/><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${onP?4.5:z?4:2.2}" ${e.c=="or"?'stroke-dasharray="7 4"':""} ${onP?'class="pflow"':""} marker-end="url(#m${e.c})"/><rect x="${mx-52}" y="${my-24}" width="104" height="30" rx="4" fill="#fff" stroke="${c}"/><text x="${mx-46}" y="${my-11}" style="font-weight:600">${e.am} ${e.as}</text><text x="${mx-46}" y="${my+1}" class="m" style="fill:var(--mu);font-size:10px">${e.h}</text></g>`}).join("");
const ns=N.filter(vn).map(n=>{const onP=onPath&&onPath.has(n.id),dim=(onPath&&!onP)||(connected&&!onPath&&!connected.has(n.id)&&sel.id!=n.id);const z=sel&&sel.t=="n"&&sel.id==n.id;
return `<g class="node" opacity="${dim?.25:1}" onclick="selN('${n.id}')">${n.id=="z"?`<circle class="pulseC" cx="${n.x+75}" cy="${n.y+32}" r="16" fill="none" stroke="${CL[n.c]}" stroke-width="2"/>`:""}<rect x="${n.x}" y="${n.y}" width="150" height="64" rx="8" fill="#fff" stroke="${z?"#111827":CL[n.c]}" stroke-width="${z?3.5:onP?3:2}"/>${z?`<rect x="${n.x-4}" y="${n.y-4}" width="158" height="72" rx="10" fill="none" stroke="#111827" stroke-width="1.4" stroke-dasharray="3 3"/>`:""}<rect x="${n.x}" y="${n.y}" width="6" height="64" rx="3" fill="${CL[n.c]}"/><text x="${n.x+14}" y="${n.y+20}" style="font-weight:600">${n.t}</text><text x="${n.x+14}" y="${n.y+37}" class="m">${n.a}</text><text x="${n.x+14}" y="${n.y+53}" style="fill:var(--mu)">${n.net}${n.risk!=null?` · risk ${n.risk}`:""}</text></g>`}).join("");
return `<svg id="gs" viewBox="0 0 1120 460" style="width:100%;height:min(64vh,540px);min-height:400px;display:block;cursor:grab;touch-action:none"><defs>${Object.entries(CL).map(([k,c])=>`<marker id="m${k}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0L8,4L0,8z" fill="${c}"/></marker>`).join("")}</defs><g id="gg"><rect x="10" y="10" width="780" height="440" rx="8" fill="#EFF6FF"/><rect x="800" y="10" width="310" height="440" rx="8" fill="#F5F3FF"/><text x="24" y="28" style="font-weight:700;fill:#2563EB">ETHEREUM</text><text x="814" y="28" style="font-weight:700;fill:#7C3AED">POLYGON</text>${es}${ns}</g></svg>`}
function render(){$("#fl").innerHTML=`<div class="fb">${seg("n",["All","Ethereum","Polygon"])}${seg("a",["All","ETH","USDT"])}${seg("dir",["All","Incoming","Outgoing"])}${seg("depth",["All","1-hop","2-hop"])}<span class="sp"></span><button class="g" onclick="zoom(1.2)">+</button><button class="g" onclick="zoom(.83)">−</button><button class="g" onclick="G.x=0;G.y=0;G.k=1;render()">FIT TO SCREEN</button><button class="g" onclick="F.n=F.a=F.dir=F.depth='All';sel=null;pathMode=false;G.x=0;G.y=0;G.k=1;render()">RESET VIEW</button></div><div class="lg" style="margin-top:8px">${LG.map(l=>`<span><b style="color:${CL[l[0]]}">■</b> ${l[1]}</span>`).join("")}<span><b style="color:#111827">▢</b> Selected node</span><span><b style="color:${CL.rd}">▬</b> Highlighted path</span></div>${pathBanner()}`;$("#gw").innerHTML=gsvg();$("#insp").innerHTML=insp();$("#ai").innerHTML=aiPanel();$("#pri").innerHTML=priorityPanel();gInit()}
const gr=render;
function hdr(v,p){const T={dashboard:"Overview",new:"Investigations",inv:"Wallet Intelligence",flow:"Fund Flow",cross:"Cross-Chain",evidence:"Evidence",monitoring:"Monitoring"}[v];return `<div class="hd"><b>${T}</b>${p[1]=="investigation"?`<span class="b ac m">${p[2]||CASE}</span>`:""}<span class="sp"></span><select aria-label="Network"><option>All networks</option><option>Ethereum</option><option>Polygon</option></select><input placeholder="Search wallet, TX or case" aria-label="Search"><span class="pf">SR</span><span class="mu">Insp. S. Rao</span></div>${p[1]=="investigation"||v=="monitoring"?'<div class="sim">Simulated blockchain data for prototype demonstration</div>':""}`}
function renderNav(){const r=location.hash||"#/dashboard";const L=[["Overview","#/dashboard"],["Investigations","#/investigations/new"],["Wallet Intelligence","#/investigation/"+CASE],["Fund Flow","#/investigation/"+CASE+"/fund-flow"],["Cross-Chain","#/investigation/"+CASE+"/cross-chain"],["Evidence","#/investigation/"+CASE+"/evidence"],["Monitoring","#/monitoring"]];$("#nav").innerHTML=L.map(l=>`<a href="${l[1]}" class="${r==l[1]?"on":""}">${l[0]}</a>`).join("")}
const V={
dashboard(){return head("Investigation Command Center","Trace, correlate and analyze blockchain fund flows from a single investigation workspace.")+`<div class="grid">${[["Active Investigations",12],["Wallets Traced","1,847"],["Cross-Chain Cases",36],["Evidence Packages",84]].map(k=>`<div class="card"><small>${k[0]}</small><div class="v">${k[1]}</div></div>`).join("")}</div>
<p><button onclick="location.hash='#/investigations/new'">New investigation</button> <button class="g" onclick="demoStart()">START DEMO</button></p>
<div class="two"><div><h2>Recent investigations</h2><div class="card tw"><table><tr><th>Case ID</th><th>Wallet</th><th>Networks</th><th>Last activity</th><th>Status</th><th>Risk indicator</th></tr>${CASES.map(c=>`<tr class="c" onclick="location.hash='#/investigation/${c[0]}'"><td class="ac">${c[0]}</td><td class="m">${c[1]}</td><td>${c[2]}</td><td>${c[3]}</td><td>${c[4]}</td><td>${rk(c[5])}</td></tr>`).join("")}</table></div>
<h2>Transactions traced, last 7 days (simulated)</h2><div class="card">${chart()}</div></div>
<div><h2>Investigation activity</h2><div class="card tl">${["New transaction detected","Cross-chain correlation found","Bridge interaction identified","Evidence package generated"].map((a,i)=>`<div class="${i==0?"new-in":""}"><b>${a}</b><br><small class="mu">${[3,14,22,41][i]} min ago · ${CASE}</small></div>`).join("")}</div></div></div>`},
new(){return head("Start New Investigation","Enter a reported wallet address to begin an evidence-linked trace.")+`<div class="card" style="max-width:640px" id="f"><label>Wallet address</label><input id="w" value="${W}" class="m"><label>Network</label><select><option>Auto Detect</option><option>Ethereum</option><option>Polygon</option></select><label>Transaction hash (optional)</label><input placeholder="0x9f31..."><label>Incident date (optional)</label><input type="date" value="2026-09-21"><label>Case reference (optional)</label><input placeholder="FIR / complaint number"><p><button onclick="trace()">START TRACE</button></p></div>`},
inv(){return head("Investigation "+CASE,"")+`<p><span class="b ok">ACTIVE INVESTIGATION</span> <span class="m mu">${W}</span></p>`+tabs("d")+`<div class="card"><b>Investigation summary</b><div class="g4" style="margin-top:10px">${[["Case",CASE],["Primary wallet","0x71A...93F2"],["Networks","Ethereum + Polygon"],["Transactions",47],["Cross-chain events",3],["Entities identified",6],["Evidence records",18]].map(k=>`<div><small>${k[0]}</small><b>${k[1]}</b></div>`).join("")}</div></div>
<div class="two" style="margin-top:14px"><div><div class="gap" style="background:#EFF6FF;border-color:var(--ac)"><b>Current investigation lead</b><p style="margin:6px 0 0">Observed activity indicates a correlated movement of funds from Ethereum to Polygon. Available evidence is consistent with bridge-mediated movement; additional evidence may be required for definitive mechanism or identity attribution.</p></div>
<h2>Transaction intelligence</h2><div class="card tw"><table><tr><th>Time</th><th>Network</th><th>TX Hash</th><th>From</th><th>To</th><th>Asset</th><th>Amount</th><th>Entity</th><th>Status</th></tr>${TX.map((x,i)=>`<tr class="c" onclick="txDrawer(${i})"><td>${x.ts}</td><td>${nb(x.blk.toString().includes("Polygon")?"Polygon":"Ethereum")}</td><td><a class="h m">${x.h}</a></td><td class="m">${x.f}</td><td class="m">${x.t}</td><td>${x.a}</td><td>${x.v}</td><td>${x.e}</td><td>${st(x.s)}</td></tr>`).join("")}</table></div><p class="mu">Select a row to open transaction details and evidence source.</p></div>
<div class="card"><b>How this finding was generated</b><ol style="padding-left:18px">${["Wallet activity retrieved","Relevant transactions filtered","Contract interaction identified","Destination-chain activity correlated","Entity intelligence applied","Investigation lead generated"].map(x=>`<li style="margin:8px 0">${x}</li>`).join("")}</ol><small class="mu">Every step links back to on-chain evidence.</small></div></div>`},
flow(){return head("Fund-Flow Reconstruction","Evidence-linked movement of assets across wallets, contracts and networks — click any node or edge to investigate.")+tabs("f")+(S.newNode?`<p class="wa">Graph updated: new destination wallet added from a monitoring alert.</p>`:"")+`<div class="card" id="fl"></div><div class="gl"><div class="card" style="padding:0;overflow:hidden" id="gw"></div><div class="side"><div class="card" id="insp"></div><div class="card" id="ai"></div><div class="card" id="pri"></div></div></div>`},
cross(){const T=[["14:32","Ethereum","18,500 USDT transferred","0x9f31...a82d","USDT","18,500","Verified"],["14:34","Ethereum","Bridge candidate contract interaction","0x81ab...e913","ETH","4.82","Candidate"],["14:35","Ethereum → Polygon","Cross-chain correlation detected","—","USDT","18,500","Correlated"],["14:38","Polygon","Destination activity detected","0x72bc...f182","USDT","18,500","Correlated"],["14:41","Polygon","18,500 USDT movement observed","0x6e02...c9a7","USDT","18,500","Review"]];
const mn=t=>`<div class="mn">${t}</div>`;
return head("Cross-Chain Intelligence","Identify and correlate asset movement across blockchain networks.")+tabs("c")+`<div class="g4">${[["Cross-Chain Events","08"],["Networks Involved","02"],["Bridge Candidates","03"],["Unresolved Movements","01"]].map(k=>`<div class="card"><small>${k[0]}</small><div class="v">${k[1]}</div></div>`).join("")}</div>
<div class="card" style="margin-top:14px"><div class="cc"><div class="ch e"><b style="color:#1D4ED8">ETHEREUM</b>${mn("Victim Wallet <span class=m>0x19C...82A1</span>")}<div class="mu" style="text-align:center">↓</div>${mn("Suspect Wallet <span class=m>0x71A...93F2</span>")}<div class="mu" style="text-align:center">↓</div>${mn("Bridge Candidate <span class=m>0xBridge...7A21</span>")}</div>
<div style="text-align:center"><b class="or">CROSS-CHAIN ACTIVITY</b><svg viewBox="0 0 190 30" width="100%"><line x1="6" y1="15" x2="176" y2="15" stroke="#EA580C" stroke-width="3" stroke-dasharray="8 4"/><path d="M176,8L188,15L176,22z" fill="#EA580C"/></svg><small class="mu">Ethereum → Polygon</small></div>
<div class="ch p"><b style="color:#6D28D9">POLYGON</b>${mn("Destination Wallet <span class=m>0x92F...18B4</span>")}<div class="mu" style="text-align:center">↓</div>${mn("Exchange Candidate <span class=m>0xEXC...91D2</span>")}</div></div>
<div class="g4" style="margin-top:12px">${[["Source transaction",hx("0x81ab...e913")],["Destination transaction",hx("0x72bc...f182")],["Time difference","3 min 42 sec"],["Asset","USDT"],["Amount","18,500"],["Correlation status","<b class=te>CORRELATED</b>"],["Confidence","<b class=ok>HIGH</b>"]].map(k=>`<div><small class="mu">${k[0]}</small>${k[1]}</div>`).join("")}</div>
<p class="mu" style="margin-bottom:0">Bridge-mediated movement consistent with observed evidence. Not a confirmed bridge.</p></div>
<div class="two" style="margin-top:14px"><div><h2 style="margin-top:0">Cross-chain timeline</h2><div class="card tw"><table><tr><th>Time</th><th>Network</th><th>Event</th><th>TX hash</th><th>Asset</th><th>Amount</th><th>Status</th></tr>${T.map(r=>`<tr><td>${r[0]}</td><td>${nb(r[1].includes("→")?"Ethereum":r[1])}${r[1].includes("→")?" "+nb("Polygon"):""}</td><td>${r[2]}</td><td>${hx(r[3])}</td><td>${r[4]}</td><td>${r[5]}</td><td>${st(r[6])}</td></tr>`).join("")}</table></div>
<h2>Cross-chain mechanism analysis</h2><div class="g4">${[["BRIDGE","Candidate","pu","Contract interaction, cross-chain correlation, destination activity"],["CEX","Not observed","mu","No exchange deposit pattern identified"],["DIRECT TRANSFER","Not observed","mu","No same-chain link between the wallets"],["UNKNOWN","Possible","wa","Cannot be ruled out with public data"]].map(m=>`<div class="card"><b>${m[0]}</b><br><span class="b ${m[2]}">${m[1]}</span><p class="mu" style="margin-bottom:0">${m[3]}</p></div>`).join("")}</div>
<h2>Evidence gap</h2><div class="gap"><b class="wa">EVIDENCE GAP</b><p>Public on-chain evidence establishes correlated cross-chain activity, but does not independently establish off-chain identity information.</p><div class="g4"><div><b>Available evidence</b><ul class="chk">${["Transaction hash","Wallet addresses","Asset","Amount","Timestamp","Smart-contract interaction","Destination activity"].map(x=>`<li>✓ ${x}</li>`).join("")}</ul></div><div><b>Not available from public chain data</b><ul style="padding:0;list-style:none" class="mu">${["Customer identity","Exchange account holder information","Private/internal records"].map(x=>`<li>○ ${x}</li>`).join("")}</ul></div></div><button onclick="req()">GENERATE EXTERNAL INTELLIGENCE REQUEST</button></div></div>
<div class="card" style="align-self:start"><b>Correlation analysis</b><dl class="kv"><dt>Source</dt><dd>Ethereum <span class="m">0x71A...93F2</span></dd><dt>Destination</dt><dd>Polygon <span class="m">0x92F...18B4</span></dd></dl><b>Signals</b><ul class="chk">${["Temporal proximity","Matching asset","Matching / correlated amount","Contract interaction observed","Destination activity observed"].map(x=>`<li>✓ ${x}</li>`).join("")}</ul><dl class="kv"><dt>Confidence</dt><dd><b class="ok">HIGH</b></dd><dt>Classification</dt><dd><b>BRIDGE CANDIDATE</b></dd><dt>Evidence</dt><dd>TX ${hx("0x81ab...e913")}<br>TX ${hx("0x72bc...f182")}</dd></dl><p><button class="g" onclick="location.hash='#/investigation/'+CASE">VIEW RELATED TRANSACTIONS</button></p><button onclick="toast('Correlation added to fund flow.');location.hash='#/investigation/'+CASE+'/fund-flow'">ADD TO FUND FLOW</button></div></div>`},
evidence(){const R=[["EV-001","Transaction","Ethereum","0x9f31...a82d","2026-09-21","18,500 USDT transferred"],["EV-002","Contract Interaction","Ethereum","0x81ab...e913","2026-09-21","Bridge candidate interaction"],["EV-003","Cross-Chain Correlation","Polygon","0x72bc...f182","2026-09-21","Destination activity correlated"]];
const sec=[["Case summary","A victim reported a transfer of 18,500 USDT to the investigated wallet. Simulated data traces onward movement to Polygon."],["Investigated wallet","EOA · first seen 2026-08-14 · 47 transactions · ETH + USDT."],["Fund-flow summary","Victim → Suspect Wallet → Intermediate Wallet → Bridge Candidate → Polygon Destination → Exchange Candidate."],["Entity intelligence","Bridge Candidate (high confidence); Exchange Candidate (inconclusive). Classifications are leads, not identity claims."],["Cross-chain findings","Consistent with bridge-mediated movement; CEX-mediated and direct transfer not supported."],["Evidence gaps","No public on-chain data establishes off-chain identity."],["Investigation leads","0xEXC...91D2 (Exchange Candidate) and 0x92F...18B4 warrant further investigation."],["Next steps","Send an authorized evidence request to the candidate exchange; keep monitoring active."]];
return head("Evidence & Investigation Report","")+tabs("e")+`<div class="card" style="max-width:860px"><div class="g4" style="margin-bottom:14px"><div><b>Available from public blockchain data</b><ul class="chk">${["Transaction hash","Wallet address","Asset","Amount","Timestamp","Contract interaction","Destination activity"].map(x=>`<li>✓ ${x}</li>`).join("")}</ul></div><div><b>Not established from public blockchain data</b><ul style="padding:0;list-style:none" class="mu">${["Real-world identity","Customer / account-holder details","Off-chain ownership information"].map(x=>`<li>○ ${x}</li>`).join("")}</ul></div></div>
<b class="ac">CHAINTRACE INDIA</b><br>DIGITAL ASSET INVESTIGATION REPORT<br><span class="mu">Case ID: ${CASE} · Generated: 2026-09-28 · Simulated data</span>
${sec.map((s,i)=>`<h2>${i+1<3?i+1:i+(i>=2?2:1)}. ${s[0]}</h2><p>${s[1]} <a class="h" onclick="toast('Evidence: see the table below and the fund-flow graph for supporting records.')">View evidence</a></p>${i==1?`<h2>3. Transaction evidence</h2><div class="tw"><table><tr><th>Evidence ID</th><th>Type</th><th>Network</th><th>TX Hash</th><th>Timestamp</th><th>Finding</th></tr>${R.map(r=>`<tr>${r.map((c,j)=>`<td class="${j==3?"m":""}">${c}</td>`).join("")}</tr>`).join("")}</table></div>`:""}`).join("")}
<p><button onclick="toast('PDF report generated successfully.')">DOWNLOAD PDF</button> <button class="g" onclick="toast('JSON export ready.')">EXPORT JSON</button> <button class="g" onclick="toast('Evidence package generated successfully.')">SHARE EVIDENCE PACKAGE</button></p></div>`},
monitoring(){return head("Investigation Monitoring","Watch investigated wallets across supported chains.")+`<div class="card"><small>MONITORED WALLET</small><b class="m">0x71A...93F2</b><br>Networks: <span class="b ac">Ethereum</span> <span class="b pu">Polygon</span> &nbsp;<span class="ok">● Monitoring Active</span></div>
<p><span class="mu">Recent alerts</span>${!S.crossAlert?` <button class="g" onclick="S.crossAlert=true;route();toast('New cross-chain activity alert received.')">SIMULATE CROSS-CHAIN ALERT</button>`:""}</p>
<div class="card new-in"><b class="wa">NEW TRANSACTION DETECTED</b><br>Wallet: <span class="m">0x71A...93F2</span> · Network: Polygon · 2,400 USDT · 3 minutes ago<p><button onclick="S.alerted=true;toast('Re-analysis complete: 1 new destination wallet.');route()">RE-ANALYSE</button></p></div>
<div class="card new-in" style="margin-top:10px"><b class="wa">NEW DESTINATION WALLET</b><br>Wallet: <span class="m">${S.alerted?"0x5D1...C3E0":"0x92F...18B4"}</span><br>Relationship: Previously observed fund-flow<p><button onclick="S.newNode=true;location.hash='#/investigation/${CASE}/fund-flow'">VIEW GRAPH</button></p></div>
${S.crossAlert?`<div class="card new-in" style="margin-top:10px"><b class="or">CROSS-CHAIN ACTIVITY DETECTED</b><br>Wallet: <span class="m">0x92F...18B4</span> · Ethereum → Polygon · just now<p><button class="g" onclick="toast('Re-analysis complete.')">RE-ANALYSE</button> <button onclick="S.newNode=true;location.hash='#/investigation/${CASE}/fund-flow'">VIEW GRAPH</button></p></div>`:""}
<p class="mu">Adapters for additional chains can be added later without changing this workflow.</p>`}};
function chart(){const d=[3,5,4,9,14,11,17],m=17;return `<svg viewBox="0 0 320 90" width="100%">${d.map((v,i)=>`<rect x="${i*45+8}" y="${80-v/m*70}" width="30" height="${v/m*70}" rx="3" fill="var(--ac)" opacity=".8"><title>${v} traces</title></rect>`).join("")}</svg>`}
function req(){modal(`<h2>External intelligence request</h2><dl><dt>Case ID</dt><dd>${CASE}</dd><dt>Known wallet</dt><dd class="m">0x71A...93F2</dd><dt>Observed transaction</dt><dd class="m">0x9f31...a82d</dd><dt>Observed date</dt><dd>2026-09-21</dd><dt>Known on-chain evidence</dt><dd>18,500 USDT forwarded, bridge deposit, Polygon receipt (EV-001 to EV-003).</dd><dt>Information requested</dt><dd class="mu">Account holder details linked to deposit address 0xEXC...91D2, if any.</dd><dt>Purpose</dt><dd>Support authorized investigation and evidence verification.</dd></dl><button onclick="closeM();toast('Request package generated.')">GENERATE REQUEST PACKAGE</button>`)}
function goDemo(h,after){location.hash=h;setTimeout(()=>{if(after)after()},40)}
const DEMO=[
{d:"Open the case file",run:()=>goDemo("#/investigation/"+CASE)},
{d:"Review the flagged transaction",run:()=>goDemo("#/investigation/"+CASE,()=>txDrawer(1))},
{d:"Open the fund-flow graph",run:()=>{closeD();goDemo("#/investigation/"+CASE+"/fund-flow")}},
{d:"Select the suspect wallet",run:()=>goDemo("#/investigation/"+CASE+"/fund-flow",()=>selN("s"))},
{d:"Trace the multi-hop investigation path",run:()=>investigatePath("s")},
{d:"Inspect the Ethereum → Polygon transition",run:()=>selE(6)},
{d:"Review cross-chain correlation evidence",run:()=>goDemo("#/investigation/"+CASE+"/cross-chain")},
{d:"Note the evidence gap",run:()=>toast("Evidence gap: identity is not established from public chain data.")},
{d:"Generate an external intelligence request",run:()=>req()},
{d:"Enable monitoring",run:()=>{closeM();goDemo("#/monitoring")}},
{d:"New cross-chain alert arrives",run:()=>{S.crossAlert=true;route();toast("New cross-chain activity alert received.")}}];
let demoI=-1;
function demoShow(){const d=$("#demo");if(demoI<0){d.style.display="none";return}d.style.display="flex";$("#demoTx").textContent=(demoI+1)+" / "+DEMO.length+" — "+DEMO[demoI].d;DEMO[demoI].run()}
function demoStart(){demoI=0;demoShow()}
function demoNext(){if(demoI<DEMO.length-1){demoI++;demoShow()}else{demoI=-1;demoShow();toast("Demo complete.")}}
function demoPrev(){if(demoI>0){demoI--;demoShow()}}
function demoEnd(){demoI=-1;demoShow()}
function trace(){const st=["Validating address","Discovering network activity","Retrieving transactions","Normalizing blockchain data","Building fund-flow graph","Running entity intelligence","Checking cross-chain activity"];
app.innerHTML=head("Tracing wallet",'<span class="m">'+W+"</span>")+`<div class="card" style="max-width:520px">${st.map((s,i)=>`<div class="step" id="s${i}">○ ${s}</div>`).join("")}</div>`;
let i=0;(function n(){if(i>0){const p=$("#s"+(i-1));p.className="step d";p.textContent="✓ "+st[i-1]}if(i<st.length){$("#s"+i).className="step n";$("#s"+i).textContent="◌ "+st[i]+"…";i++;setTimeout(n,650)}else{toast("Trace complete.");setTimeout(()=>location.hash="#/investigation/"+CASE,700)}})()}
function route(){closeD();renderNav();const p=(location.hash||"#/dashboard").split("/");let v="dashboard";
if(p[1]=="investigations")v="new";else if(p[1]=="investigation")v=p[3]=="fund-flow"?"flow":p[3]=="cross-chain"?"cross":p[3]=="evidence"?"evidence":"inv";else if(p[1]=="monitoring")v="monitoring";
app.innerHTML=hdr(v,p)+V[v]();if(v=="flow")gr();window.scrollTo(0,0)}
addEventListener("hashchange",route);addEventListener("keydown",e=>{if(e.key=="Escape"){closeD();closeM()}});route();


// Expose functions referenced by inline HTML event handlers (onclick="...")
// to the global scope, since this file is loaded as an ES module.
Object.assign(window, {
  closeD,
  closeM,
  demoEnd,
  demoNext,
  demoPrev,
  demoStart,
  explorer,
  investigatePath,
  openEv,
  render,
  req,
  route,
  selE,
  selN,
  toast,
  trace,
  txDrawer,
  zoom
});
